### ISSUE TITLE
Do feature detection instructions need to appear in Wasm syntax?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/feature-detection#2]
The overview currently describes feature detection as being resolved at decode time so that `feature_block` is decoded as either a normal block or as an `unreachable` and `features.supported` is decoded as either a 0 or 1. This is a convenient framing of the proposal, but it is also unprecedented. Should we instead treat `feature_block` and `features.supported` as normal instructions and include them in the abstract syntax and validation algorithms?

@rossberg, I'd be particularly interested in your thoughts on this.

**Comment by rossberg** [comment]
I'm not sure they can be resolved later than decoding time, since a feature block has to be accepted for any arbitrary byte sequence. So it cannot be turned into an AST in any uniform way – unless we break the phase distinction and have validation & execution call back into decoding, which would be super nasty and not very natural.

The problem with resolving it during decoding is that, technically, we now have to introduce non-determinism into decoding – i.e., intentionally define an ambiguous binary grammar. That also is rather nasty, and does not increase my excitement about this feature. ;)
